apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: external-secrets
  namespace: argocd

spec:
  project: default

  sources:

    # External Secrets Helm chart
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.18.2

      helm:
        valueFiles:
          - $values/root/platform/external-secrets/values.yaml

    # GitOps repo containing values.yaml
    - repoURL: https://github.com/marcelodevops/argocdlab.git
      targetRevision: main
      ref: values

    # Git manifests
    - repoURL: https://github.com/marcelodevops/argocdlab.git
      targetRevision: main
      path: root/platform/external-secrets/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
