apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: vault
  namespace: argocd

spec:
  project: default

  sources:

    # Vault Helm chart
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.30.0

      helm:
        valueFiles:
          - $values/platform/vault/values.yaml

    # Your GitOps repo containing values.yaml
    - repoURL: https://github.com/marcelodevops/gitops.git
      targetRevision: HEAD
      ref: va

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
